### ISSUE TITLE
Reports are not getting generated

### ISSUE THREAD

**Issue by IdanAdar** [raelgc/jasmine-xml-reporter#1]
Hi,

I am using Jasmine for a project, and I am attempting to integrate it with Jenkins.
I noticed that in the examples it is being executed from `jasmine-xml-reporter`. Is this a requirement? (npm newb...)

This is what I am doing:

```
mkdir testresults
./node_modules/.bin/jasmine --junitreport --output=testresults/
```

I first created `testresults` because apparently it is not being created otherwise. 
Is it supposed to?

Second,
I also notice that whether the test fails or succeeds, no report is actually generated inside `testresult`.

I must be missing something obvious... because it _is_ running:

```
Started
.


1 spec, 0 failures
Finished in 0.005 seconds
```

I have the following packages installed:

* jasmine 2.5.0
* jasmine-core 2.5.2
* jasmine-xml-reporter 1.0.6
* jasmine-reporters 2.2.0

**Comment by raelgc** [comment]
Hi @IdanAdar and thanks for raising this issue.

In theory, you should run the examples with `jasmine-xml-reporter`.

But probably requiring `jasmine-xml-reporter/boot.js` will be enough.
