### ISSUE TITLE
Question: how do I pass the output and --junitreport parameters via jasmine.json?

### ISSUE THREAD

**Issue by tomer-ben-david** [raelgc/jasmine-xml-reporter#6]
I tried the below with no success:

```
{
  "spec_dir": "src/test",
  "spec_files": [
    "ts/**/*.test.ts"
  ],
  "reporters": [
    {
      "name": "jasmine-reporters#JUnitXmlReporter",
      "options": {
        "output": "../dist"
      }
    }
  ]
}
```

**Comment by raelgc** [comment]
@tomer-ben-david: the way you want to use, you'll use JasmineReporters directly, so better if you ask this question in [their repo](https://github.com/larrymyers/jasmine-reporters).

If you want to use this package, you can change your `test` call in `scripts` section from your `package.json` to be:

```javascript
  "scripts": {
    "test": "./node_modules/jasmine-xml-reporter/bin/jasmine.js --junitreport --output=../dist"
  },
```
    

So when running `npm test` it'll work as expected.

**Comment by tomer-ben-david** [comment]
thanks, i use jasmine-ts so it looks like it won't be available for me,
i'll try checking out karma, thanks anyway! :)
