### ISSUE TITLE
Request: option to configure output filename

### ISSUE THREAD

**Issue by nelsonkyshin** [raelgc/jasmine-xml-reporter#7]
Thanks for providing this, it's super easy to use. I see the prefix is hardcoded to 'results' at the moment which results in a file results.xml. Is it possible to make the filename configurable? Or is there another way to change the output filename?

Thanks.
Nelson

**Comment by raelgc** [comment]
@nelsonkyshin Thank you for the idea. I just published this improvement. Use `--filePrefix` option. 

Example: if I want a file named `foobar.xml`, I'll use: `--filePrefix=foobar`.

Let me know if it works and, case yes, close this issue, please.

**Comment by nelsonkyshin** [comment]
Hi @raelgc thanks so much for following up. This is great! Closing the issue now
