### ISSUE TITLE
--output is broken in 1.2.0

### ISSUE THREAD

**Issue by brantburnett** [raelgc/jasmine-xml-reporter#9]
Changes to support file prefix customization appear to have broken the --output argument.

I believe the issue is here: https://github.com/raelgc/jasmine-xml-reporter/commit/f70821700a060a3fbfb4b9d227bf641cf0de80ed#diff-fe60a8aed4b3103661f9d88361346b0dR13

It's assigning the value to the attribute "output", but the actual object attribute name appears to be "output_dir".  So instead it always outputs to "./".

**Comment by raelgc** [comment]
@brantburnett Sorry for this. I just published a fix. Let me know if it works.

**Comment by brantburnett** [comment]
This appears to have fixed it, thanks!
